name: CI Workflow
on:
  push: null
defaults:
  run:
    working-directory: go/src/sigs.k8s.io/work-api
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.22.12
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.58.0
        only-new-issues: false
        args: --timeout 3m0s
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: go/src/sigs.k8s.io/work-api
    - name: install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.12
    - name: images
      run: make docker-build
      env:
        GOPATH: /home/runner/work/work-api/work-api/go
    - name: setup kind
      uses: engineerd/setup-kind@v0.6.2
      with:
        version: v0.11.1
    - name: Load image on the nodes of the cluster
      run: 'kind load docker-image --name=kind work-api-controller:latest

        '
    - name: Run e2e test
      run: 'make test-e2e

        '
      env:
        KUBECONFIG: /home/runner/.kube/config
  verify:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: go/src/sigs.k8s.io/work-api
    - name: install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.12
    - name: verify
      run: hack/verify-all.sh -v
      env:
        GOPATH: /home/runner/work/work-api/work-api/go
    - name: checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: go/src/sigs.k8s.io/work-api
    - name: install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.12
    - name: make test
      run: make test
      env:
        GOPATH: /home/runner/work/work-api/work-api/go
